version: 4.2.{build}

os: Visual Studio 2015

environment:
  matrix:
    - VSVER: Visual Studio 14 2015 Win64

platform:
  - x64

configuration:
  - Release

install:
  - git submodule -q update --init

before_build:
  - md %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake -G"%VSVER%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_META_EXAMPLES=OFF -DENABLE_TESTING=ON ..
  - cd ..

build:
  parallel: true
  project: build\shogun.sln
  verbosity: minimal

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ctest --output-on-failure -j 2
  - cd ..
